
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:3000'
    volumes:
      - /srv/volumes/system-monitora/ftp/_data:/srv/projects/ftp
      - /srv/volumes/system-monitora/ftp/_data:/srv/projects/images-images-yolo
      - /srv/volumes/system-monitora/ftp/_data:/srv/projects/ftp/
