
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:3333'
    devices:
      - "/dev/rtc:/dev/rtc:ro" # DATE
    volumes:
      - "/etc/localtime:/etc/localtime:ro"  # DATE
      - shared-data:/srv/projects/ftp
      # - /srv/volumes/system-monitora/ftp/_data:/srv/projects/ftp
      - /srv/volumes/system-monitora-yolo/app/img/_data:/srv/projects/images-yolo


volumes:
  shared-data: